/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getMediaUrls(page: string, absoluteOnly: boolean, domain?: string | undefined | null): Array<string>
export declare function getHighResUrl(url: string): string
